spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8670/eureka/
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
server:
  port:8670
