spring:
  application:
    name: eureka-server
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
eureka:
  client:
#    serviceUrl:
#      defaultZone: http://localhost:8670/eureka/
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
server:
  port: 8670
